### PR TITLE
New version of client based on different generator

### PR DESCRIPTION
**Pull request by TimonOmsk**
## Description

This PR completely replaces old client with a new one build with a different generator

### Type of change

* [ ] Bug fix (non-breaking change which fixes an issue)
* [ ] New feature (non-breaking change which adds functionality)
* [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)
* [ ] This change requires a documentation update

### CODE REVIEW

**Comment by denisvmedia** [comment]
It looks like the client misses `go.sum`.

**Comment by denisvmedia** [comment]
Another note: can we have github actions that will check that what we have in `Makefile` works without issues? I do realize that we cannot easily check the client itself, but at least he commands should work as expected.

**Comment by denisvmedia** [comment]
`go.work.sum` should be ignored (i.e. committed according to this doc: https://go.googlesource.com/proposal/+/master/design/45713-workspace.md#preventing-files-from-being-checked-in-to-repositories).

**Comment by denisvmedia** [comment]
It also looks like the docs don't include a full example anymore. They should at least mention how to include the new version:

`import "github.com/veeamhub/veeam-vbr-sdk-go/client/v2"`

**Comment by denisvmedia** [comment]
Another question: why do we need the fixer tool as a module? I.e. why don't we have a single-module repo instead?

**Comment by TimonOmsk** [comment]
> Also you should create a v2 branch from master and the PR should look into that branch. The release of the client will then be the version 2 (as it is incompatible with the version 1).

> Another note: can we have github actions that will check that what we have in Makefile works without issues? I do realize that we cannot easily check the client itself, but at least he commands should work as expected.

That's why I've proposed to create a new repository for this client. First of all we don't have access to VeeamHub repository. Only @dsu-igeek  has. We asked for access but a got a polite answer that "Dave already has access. It should be enough". 

Also, we could work directly with master, without any v2 branches and so on.

**Comment by TimonOmsk** [comment]
> Another question: why do we need the fixer tool as a module? I.e. why don't we have a single-module repo instead?

I think of this repository as about a tool, not only the client. We gives tool to work with specification, regenerate client, if somebody needs a new(or slightly changed version), and so on. We can release only module with client, but I think having all the tools inside the repo is good

**Comment by TimonOmsk** [comment]
> It also looks like the docs don't include a full example anymore. They should at least mention how to include the new version:

You're right about example. I think maybe it's better to create standalone example? Like create a new "example" directory and put couple of example there. WDYT?

**Comment by TimonOmsk** [comment]
> go.work.sum should be ignored (i.e. committed according to this doc: https://go.googlesource.com/proposal/+/master/design/45713-workspace.md#preventing-files-from-being-checked-in-to-repositories).

Here is ongoing discussion about `go.work` in repos - https://github.com/golang/go/issues/53502
I think in this case go.work in repo is a good idea. I'll remove `go.work` from `.gitignore `and return it to repo

**Comment by denisvmedia** [comment]
> I think of this repository as about a tool, not only the client. We gives tool to work with specification, regenerate client, if somebody needs a new(or slightly changed version), and so on. We can release only module with client, but I think having all the tools inside the repo is good

I'm still not convinced that having two separate modules in one repo is enough justified. The tool is a helper stuff for the client itself and it doesn't deserve its own module to my vision. But there is a chance I'm missing something.

> That's why I've proposed to create a new repository for this client. First of all we don't have access to VeeamHub repository. Only @dsu-igeek has. We asked for access but a got a polite answer that "Dave already has access. It should be enough".
>
> Also, we could work directly with master, without any v2 branches and so on.

OK, but still we need to solve it somehow, otherwise we are applying a bad practice here by publishing a completely new client, which is not even semi-compatible with the v1. I think, we should either gain access to create `v2` branch, or have someone to do that for us, or - at worst - use another repo where we have full rights.

> You're right about example. I think maybe it's better to create standalone example? Like create a new "example" directory and put couple of example there. WDYT?

Yes, why not. BTW, one of the options is having an idiomatic go approach `example_test.go`, see https://go.dev/blog/examples for more details.

> Here is ongoing discussion about go.work in repos - https://github.com/golang/go/issues/53502
> I think in this case go.work in repo is a good idea. I'll remove go.work from .gitignore and return it to repo

As soon as we make it a single-module repo, the `work` file won't be needed anyway. Having a multi-module brings unnecessary complications for a repo that is its by nature expected to be a single-module one (there are barely existing a multi-module repos in the wild that serve for a single purpose to provide a single library and that are multi-module ones; I'm open however to change my mind if we have at least a couple of examples who does that for a library).

**Comment by TimonOmsk** [comment]
I've fixed most of comments by @denisvmedia, except the one with Github Actions. @AlekseyBlokhin asked again about permissions. 

BTW, what should we do with Readme in the master branch? It is possible to change default branch to show the v2?

@denisvmedia could you please re-review

**Review by denisvmedia — APPROVED** [review]
Good question about the Readme in master. I suggest we update it separately as soon as we get it merged in the main repo. Also regarding the GitHub actions, I guess we can have them in a separate PR.

And thank you @TimonOmsk for your efforts. Looks good to me.

**Pull request merged**
